### ISSUE TITLE
Fill width with dots

### ISSUE THREAD

**Issue by HD-AD** [EyalBira/loading-dots#4]
Is there a way to fill the whole width with "dots"? Currently I'm setting the dots by setting `app:LoadingDots_dots_count="12"` but is there a way to fill the entire remaining space?

**Comment by EyalBira** [comment]
You want to have dots to fill the parent view width? if so, this is not supported (nor I think it should be).

You can calculate it yourself:
`required_dots = parent_width / (#dots*dots_size+ (#dots-1)*space_size)`
Then use that value for the widget.

**Comment by HD-AD** [comment]
@EyalBira It doesn't work I get the following error:

`java.lang.IllegalStateException: Can't change properties while animation is running!`

And this is how I implemented it:

```
//Getting the dot size
int dotsSize = ld.getDotsSize();

//Getting the space between the dots
int dotSpacing = ld.getDotsSpace();

//Adding the dotsSize and dotSpacing
int entireDotwidth = dotsSize + dotSpacing;

//Getting the width of the view
int mViewWidth = mView.getWidth();

//Calculate the amount of dots (this returns 16)
int dotAmount = mViewWidth/entireDotwidth;

//Then I try to set it (this is where the error comes from)
ld.setDotsCount(dotAmount);

```

**Comment by HD-AD** [comment]
Never mind I fixed it by stopping the animation just before I set the dots amount. Regarding you saying `(nor I think it should be)` - with android creating for all screen sizes is important and including this in the library will make it a lot easier for developers using the library.

Oh and another thing, I'm displaying this in a dialog and I had to get the width of the dialog in a `Runnable` making this even more complex to implement. Libraries = simplicity, that is why people use libraries. Just saying.

**Comment by EyalBira** [comment]
@HD-AD glad to hear you were able to make it work! 

Like with everything else you use, there are common scenarios - and there are less common scenarios. A library can't (and should not) support every scenario possible. The scenario you need, where the dots fill up the entire width - is not a common scenario for the intended purpose of this library. 

The main purpose of this library is "Typing" loading dots effect for chats. Having said that, open source is all about collaborating, I encourage you to clone the project and add the code to support this scenario and create a Pull Request. I will be more than happy to merge it in for the benefit of other community members.

( BTW there are better ways to calculate the width than with a Runnable :) )

Happy Coding!
